"""initial migration

Revision ID: 3108c8a2cc8e
Revises: None
Create Date: 2015-03-09 16:14:17.526119

"""

# revision identifiers, used by Alembic.
revision = '3108c8a2cc8e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
